/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Code.*;
import java.sql.ResultSet;

/*
Nama        :   Dhifan Fadhilah Aditya - 140810210042
                Aryan Dafi Maulana – 140810210012
        	Akmal Azzary Megaputra - 140810210048
*/

public class TransaksiForm extends javax.swing.JFrame {

    /**
     * Creates new form TransaksiForm
     */
    public TransaksiForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        idPeminjamanLabel = new javax.swing.JLabel();
        idPegawaiLabel = new javax.swing.JLabel();
        idPelLabel = new javax.swing.JLabel();
        jenisLabel = new javax.swing.JLabel();
        tanggalLabel = new javax.swing.JLabel();
        lamaLabel = new javax.swing.JLabel();
        idPegawaiField = new javax.swing.JTextField();
        idPinjamField = new javax.swing.JTextField();
        idPelField = new javax.swing.JTextField();
        tglComboBox = new javax.swing.JComboBox<>();
        blnComboBox = new javax.swing.JComboBox<>();
        thnField = new javax.swing.JTextField();
        lamaField = new javax.swing.JTextField();
        generateButton = new javax.swing.JButton();
        idMobilField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        kembaliLabel = new javax.swing.JLabel();
        biayaLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        biayaField = new javax.swing.JTextField();
        totalField = new javax.swing.JTextField();
        kembaliField = new javax.swing.JTextField();
        savePinjamButton = new javax.swing.JButton();
        cancelPinjamButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        idSearchLabel = new javax.swing.JLabel();
        idSearchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        tglKembaliLabel = new javax.swing.JLabel();
        idPelResultLabel = new javax.swing.JLabel();
        idMobilResultLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lamaResultLabel = new javax.swing.JLabel();
        biayaResultLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idPelResult = new javax.swing.JTextField();
        idMobilResult = new javax.swing.JTextField();
        tglPinjamResult = new javax.swing.JTextField();
        lamaResult = new javax.swing.JTextField();
        biayaResult = new javax.swing.JTextField();
        tglKembaliResult = new javax.swing.JTextField();
        dendaResultLabel = new javax.swing.JLabel();
        prosesButton = new javax.swing.JButton();
        telatResult = new javax.swing.JTextField();
        dendaResult = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        totalResult = new javax.swing.JLabel();
        totalBiayaResult = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMobilTable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transaction");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Transaksi Peminjaman");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Peminjaman"));

        idPeminjamanLabel.setText("Id Peminjaman :");

        idPegawaiLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idPegawaiLabel.setText("Id Pegawai :");

        idPelLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idPelLabel.setText("Id Pelanggan :");

        jenisLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jenisLabel.setText("Id Mobil :");

        tanggalLabel.setText("Tanggal Pinjam :");

        lamaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lamaLabel.setText("Lama Pinjam :");

        idPegawaiField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idPegawaiFieldFocusLost(evt);
            }
        });
        idPegawaiField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idPegawaiFieldKeyPressed(evt);
            }
        });

        idPinjamField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idPinjamFieldFocusLost(evt);
            }
        });
        idPinjamField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idPinjamFieldKeyPressed(evt);
            }
        });

        idPelField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idPelFieldFocusLost(evt);
            }
        });
        idPelField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idPelFieldKeyPressed(evt);
            }
        });

        tglComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tgl", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        blnComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "bln", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        thnField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                thnFieldKeyPressed(evt);
            }
        });

        lamaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lamaFieldKeyPressed(evt);
            }
        });

        generateButton.setText("Generate");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        idMobilField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idMobilFieldFocusLost(evt);
            }
        });

        jLabel3.setText("hari");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lamaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idPeminjamanLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idPegawaiLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idPelLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jenisLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tanggalLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idMobilField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idPegawaiField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idPinjamField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                                .addComponent(tglComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(blnComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(thnField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(idPelField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lamaField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idPegawaiLabel)
                    .addComponent(idPegawaiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idPeminjamanLabel)
                    .addComponent(idPinjamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idPelLabel)
                    .addComponent(idPelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisLabel)
                    .addComponent(idMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanggalLabel)
                    .addComponent(tglComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blnComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lamaLabel)
                    .addComponent(lamaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(generateButton)
                .addContainerGap())
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Result"));

        kembaliLabel.setText("Tanggal Kembali :");

        biayaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        biayaLabel.setText("Biaya Sewa :");

        totalLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalLabel.setText("Total Biaya :");

        biayaField.setEditable(false);

        totalField.setEditable(false);

        kembaliField.setEditable(false);

        savePinjamButton.setText("Save");
        savePinjamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePinjamButtonActionPerformed(evt);
            }
        });

        cancelPinjamButton.setText("Cancel");

        jLabel4.setText("/hari");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kembaliLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(biayaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(savePinjamButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelPinjamButton))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(biayaField)
                            .addComponent(totalField)
                            .addComponent(kembaliField, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(biayaLabel)
                    .addComponent(biayaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel)
                    .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kembaliLabel)
                    .addComponent(kembaliField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savePinjamButton)
                    .addComponent(cancelPinjamButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Peminjaman", jPanel2);

        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Transaksi Pengembalian");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));

        idSearchLabel.setText("Id Peminjaman :");

        idSearchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idSearchFieldKeyPressed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(idSearchLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchButton)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idSearchLabel)
                    .addComponent(idSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Result"));

        tglKembaliLabel.setText("Tanggal Kembali :");

        idPelResultLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idPelResultLabel.setText("Id Pelanggan :");

        idMobilResultLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idMobilResultLabel.setText("Id Mobil :");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Tanggal Pinjam :");

        lamaResultLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lamaResultLabel.setText("Lama Pinjam :");

        biayaResultLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        biayaResultLabel.setText("Biaya Sewa :");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Telat :");

        idPelResult.setEditable(false);

        idMobilResult.setEditable(false);

        tglPinjamResult.setEditable(false);

        lamaResult.setEditable(false);

        biayaResult.setEditable(false);

        tglKembaliResult.setEditable(false);

        dendaResultLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dendaResultLabel.setText("Denda :");

        prosesButton.setText("Proses");
        prosesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesButtonActionPerformed(evt);
            }
        });

        dendaResult.setEditable(false);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        totalResult.setText("Total Biaya :");

        totalBiayaResult.setEditable(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalResult)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idMobilResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tglKembaliLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idPelResultLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lamaResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(biayaResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(dendaResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalBiayaResult, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(prosesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idPelResult)
                    .addComponent(idMobilResult, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(tglPinjamResult, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(lamaResult, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(biayaResult, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(tglKembaliResult, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(telatResult)
                    .addComponent(dendaResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idPelResultLabel)
                    .addComponent(idPelResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idMobilResultLabel)
                    .addComponent(idMobilResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tglPinjamResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lamaResultLabel)
                    .addComponent(lamaResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(biayaResultLabel)
                    .addComponent(biayaResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglKembaliLabel)
                    .addComponent(tglKembaliResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(telatResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prosesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dendaResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dendaResultLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveButton)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalResult)
                        .addComponent(totalBiayaResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pengembalian", jPanel3);

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Daftar Mobil");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        listMobilTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Mobil", "Jenis Mobil", "Sewa/hari", "Stok"
            }
        ));
        listMobilTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                listMobilTablePropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(listMobilTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Mobil", jPanel4);

        backButton.setForeground(new java.awt.Color(255, 0, 0));
        backButton.setText("Back to Menu");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        RentForm form = new RentForm();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void listMobilTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_listMobilTablePropertyChange
        // TODO add your handling code here:
        Koneksi kon = new Koneksi();
        ResultSet rs = null;
        int i = 0;
        try{
            rs = kon.getData("select * from cars");
            while(rs.next()){
                listMobilTable.setValueAt(rs.getString("car_id"), i, 0);
                listMobilTable.setValueAt(rs.getString("car_name"), i, 1);
                listMobilTable.setValueAt(rs.getString("rent"), i, 2);
                listMobilTable.setValueAt(rs.getString("stock"), i, 3);
                i++;
            }
            rs.close();
        } catch(Exception e){

        }
    }//GEN-LAST:event_listMobilTablePropertyChange

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        // TODO add your handling code here:
        Koneksi kon = new Koneksi();
        ResultSet rs = null;
        try{
            rs = kon.getData("select * from cars where car_id = '"+idMobilField.getText()+"'");
            while(rs.next()){
                biayaField.setText(rs.getString("rent"));
                int k, l, m, n, o;
                k = Integer.valueOf(lamaField.getText()).intValue();
                l = Integer.valueOf(""+tglComboBox.getSelectedItem()).intValue();
                m = Integer.valueOf(biayaField.getText()).intValue();
                n = k + l;
                o = k * m;
                totalField.setText(String.valueOf(o));
                kembaliField.setText(thnField.getText()+"-"+blnComboBox.getSelectedItem()+"-"+String.valueOf(n));
            }
            rs.close();
        } catch(Exception e){
            
        }
    }//GEN-LAST:event_generateButtonActionPerformed

    private void savePinjamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePinjamButtonActionPerformed
        // TODO add your handling code here:
        Peminjaman pem = new Peminjaman();
        pem.setIdPinjam(idPinjamField.getText());
        pem.setIdCust(idPelField.getText());
        pem.setIdPegawai(idPegawaiField.getText());
        pem.setIdMobil(idMobilField.getText());
        pem.setPhari(""+tglComboBox.getSelectedItem());
        pem.setPbulan(""+blnComboBox.getSelectedItem());
        pem.setPtahun(thnField.getText());
        pem.setLama(lamaField.getText());
        pem.setTglKembali(kembaliField.getText());
        pem.setBiaya(biayaField.getText());
        pem.insertPeminjaman();
        javax.swing.JOptionPane.showMessageDialog(null, "Insert Success!");
        
        idPinjamField.setText(null);
        idPelField.setText(null);
        idPegawaiField.setText(null);
        idMobilField.setText(null);
        tglComboBox.setSelectedIndex(0);
        blnComboBox.setSelectedIndex(0);
        thnField.setText(null);
        lamaField.setText(null);
        kembaliField.setText(null);
        biayaField.setText(null);
    }//GEN-LAST:event_savePinjamButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        Koneksi kon = new Koneksi();
        ResultSet rs = null;
        try{
            rs = kon.getData("select * from peminjaman where id_pinjam = '"+idSearchField.getText()+"'");
            while(rs.next()){
                idPelResult.setText(rs.getString("id_cust"));
                idMobilResult.setText(rs.getString("id_mobil"));
                tglPinjamResult.setText(rs.getString("tgl_pinjam"));
                lamaResult.setText(rs.getString("lama_pinjam")+" hari");
                biayaResult.setText(rs.getString("biaya"));
                tglKembaliResult.setText(rs.getString("tgl_kembali"));
            }
            rs.close();
        } catch(Exception e){
            
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void prosesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesButtonActionPerformed
        // TODO add your handling code here:
        int a, b, c;
        a = Integer.valueOf(telatResult.getText()).intValue();
        b = a * 100000;
        c = Integer.valueOf(biayaResult.getText()).intValue() + b;
        dendaResult.setText(String.valueOf(b));
        totalBiayaResult.setText(String.valueOf(c));
    }//GEN-LAST:event_prosesButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        Peminjaman pem = new Peminjaman();
        pem.setIdPinjam(idSearchField.getText());
        pem.setTelat(telatResult.getText());
        pem.setDenda(dendaResult.getText());
        pem.setBiaya(totalBiayaResult.getText());
        pem.updatePeminjaman();
        javax.swing.JOptionPane.showMessageDialog(null, "Update Success!");
    }//GEN-LAST:event_saveButtonActionPerformed

    private void idPegawaiFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idPegawaiFieldFocusLost
        // TODO add your handling code here:
        Koneksi kon = new Koneksi();
        ResultSet rs = null;
        try{
            rs = kon.getData("select * from user where id = '"+idPegawaiField.getText()+"'");

            if(rs.next() == false){
                javax.swing.JOptionPane.showMessageDialog(null, "Id pegawai tidak diketahui");
                idPegawaiField.setText(null);
            } else{
                do{
                    
                }while(rs.next());
            }
         
            rs.close();
            
        } catch(Exception e){

        }
    }//GEN-LAST:event_idPegawaiFieldFocusLost

    private void idPinjamFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idPinjamFieldFocusLost
        // TODO add your handling code here:
        Koneksi kon = new Koneksi();
        ResultSet rs = null;
        try{
            rs = kon.getData("select * from peminjaman where id_pinjam = '"+idPinjamField.getText()+"'");
            while(rs.next()){
                javax.swing.JOptionPane.showMessageDialog(null, "Id sudah terpakai");
                idPinjamField.setText("");
            }
            rs.close();
            
        } catch(Exception e){

        }
    }//GEN-LAST:event_idPinjamFieldFocusLost

    private void idPelFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idPelFieldFocusLost
        // TODO add your handling code here:
        Koneksi kon = new Koneksi();
        ResultSet rs = null;
        try{
            rs = kon.getData("select * from customer where customer_id = '"+idPelField.getText()+"'");
            if(rs.next() == false){
                javax.swing.JOptionPane.showMessageDialog(null, "Id pelanggan tidak diketahui");
                idPelField.setText(null);
            } else{
                do{
                    
                }while(rs.next());
            }
            rs.close();
            
        } catch(Exception e){

        }
    }//GEN-LAST:event_idPelFieldFocusLost

    private void idMobilFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idMobilFieldFocusLost
        // TODO add your handling code here:
        Koneksi kon = new Koneksi();
        ResultSet rs = null;
        try{
            rs = kon.getData("select * from cars where car_id = '"+idMobilField.getText()+"'");
            
            if(rs.next() == false){
                javax.swing.JOptionPane.showMessageDialog(null, "Id mobil tidak diketahui");
                idMobilField.setText(null);
            } else{
                do{
                    
                }while(rs.next());
            }
            
            rs.close();
            
        } catch(Exception e){

        }
    }//GEN-LAST:event_idMobilFieldFocusLost

    private void idPegawaiFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idPegawaiFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == 0x0A){
            idPinjamField.requestFocus();
        }
    }//GEN-LAST:event_idPegawaiFieldKeyPressed

    private void idPinjamFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idPinjamFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == 0x0A){
            idPelField.requestFocus();
        }
    }//GEN-LAST:event_idPinjamFieldKeyPressed

    private void idPelFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idPelFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == 0x0A){
            idMobilField.requestFocus();
        }
    }//GEN-LAST:event_idPelFieldKeyPressed

    private void thnFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_thnFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == 0x0A){
            lamaField.requestFocus();
        }
    }//GEN-LAST:event_thnFieldKeyPressed

    private void lamaFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lamaFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == 0x0A){
            generateButton.requestFocus();
        }
    }//GEN-LAST:event_lamaFieldKeyPressed

    private void idSearchFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idSearchFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == 0x0A){
            searchButton.requestFocus();
        }
    }//GEN-LAST:event_idSearchFieldKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField biayaField;
    private javax.swing.JLabel biayaLabel;
    private javax.swing.JTextField biayaResult;
    private javax.swing.JLabel biayaResultLabel;
    private javax.swing.JComboBox<String> blnComboBox;
    private javax.swing.JButton cancelPinjamButton;
    private javax.swing.JTextField dendaResult;
    private javax.swing.JLabel dendaResultLabel;
    private javax.swing.JButton generateButton;
    private javax.swing.JTextField idMobilField;
    private javax.swing.JTextField idMobilResult;
    private javax.swing.JLabel idMobilResultLabel;
    private javax.swing.JTextField idPegawaiField;
    private javax.swing.JLabel idPegawaiLabel;
    private javax.swing.JTextField idPelField;
    private javax.swing.JLabel idPelLabel;
    private javax.swing.JTextField idPelResult;
    private javax.swing.JLabel idPelResultLabel;
    private javax.swing.JLabel idPeminjamanLabel;
    private javax.swing.JTextField idPinjamField;
    private javax.swing.JTextField idSearchField;
    private javax.swing.JLabel idSearchLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jenisLabel;
    private javax.swing.JTextField kembaliField;
    private javax.swing.JLabel kembaliLabel;
    private javax.swing.JTextField lamaField;
    private javax.swing.JLabel lamaLabel;
    private javax.swing.JTextField lamaResult;
    private javax.swing.JLabel lamaResultLabel;
    private javax.swing.JTable listMobilTable;
    private javax.swing.JButton prosesButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton savePinjamButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel tanggalLabel;
    private javax.swing.JTextField telatResult;
    private javax.swing.JComboBox<String> tglComboBox;
    private javax.swing.JLabel tglKembaliLabel;
    private javax.swing.JTextField tglKembaliResult;
    private javax.swing.JTextField tglPinjamResult;
    private javax.swing.JTextField thnField;
    private javax.swing.JTextField totalBiayaResult;
    private javax.swing.JTextField totalField;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalResult;
    // End of variables declaration//GEN-END:variables
}
